//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MedidoresWebModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lectura
    {
        public int id_lectura { get; set; }
        public string numero_serie { get; set; }
        public Nullable<System.DateTime> fecha_lectura { get; set; }
        public Nullable<System.TimeSpan> hora_lectura { get; set; }
        public Nullable<int> valor_consumo { get; set; }
    }
}
